var str = '<div class="cover"><div class="inner inner-login"><div class="close"></div><p class="title">登录</p><div class="input-group"><i class="person i"></i><input type="tel" placeholder="请输入手机号"></div><div class="input-group"><i class="pw i"></i><input type="password" placeholder="请输入密码"></div><div class="input-group" style="border:none;margin:0 auto"><input type="text" class="verify-input" placeholder="请输入验证码"><div class="verify"></div></div><div class="input-group a-txt" style="border:none;margin:0 auto;height:52px;line-height:52px"><a href="javascript:void (0)" class="register">免费注册</a> <a href="javascript:void (0)" class="reset">忘记密码</a></div><div class="btn">登录</div></div><div class="inner inner-register"><div class="close"></div><p class="title">注册</p><div class="input-group"><i class="person i"></i><input type="tel" placeholder="请输入手机号"></div><div class="input-group"><i class="pw i"></i><input type="password" placeholder="请输入密码"></div><div class="input-group"><i class="pw i"></i><input type="password" placeholder="确认密码"></div><div class="input-group" style="border:none"><input type="text" class="verify-input" placeholder="请输入密码"><div class="verify"></div></div><div class="input-group" style="border:none;margin:0 auto"><input type="text" class="verify-input" placeholder="请输入验证码"><div class="verify-btn">获取验证码</div></div><div class="input-group a-txt" style="border:none;margin:0 auto;height:52px;line-height:52px"><a href="javascript:void (0)" class="back">返回登录</a> <a href="javascript:void (0)" class="reset">忘记密码</a></div><div class="btn">注册</div><div class="agree">点击“注册”即表示您同意 <a href="">《全联征信协议》</a></div></div><div class="inner inner-reset"><div class="close"></div><p class="title">重置密码</p><div class="input-group"><i class="person i"></i><input type="tel" placeholder="请输入手机号"></div><div class="input-group"><i class="pw i"></i><input type="password" placeholder="请输入新密码"></div><div class="input-group"><i class="pw i"></i><input type="password" placeholder="确认密码"></div><div class="input-group" style="border:none;margin:0 auto"><input type="text" class="verify-input" placeholder="请输入验证码"><div class="verify-btn">获取验证码</div></div><div class="input-group a-txt" style="border:none;margin:0 auto;height:52px;line-height:52px"><a href="javascript:void (0)" class="register">免费注册</a> <a href="javascript:void (0)" class="back">返回登录</a></div><div class="btn">确定</div></div></div>';
var body = document.getElementsByTagName('body')[0];
body.innerHTML += str;
$('.register').click(function () {
    $(this).parent().parent().hide();
    $('.cover .inner-register').show()
});
$('.reset').click(function () {
    $(this).parent().parent().hide();
    $('.cover .inner-reset').show()
})
$('.back').click(function () {
    $(this).parent().parent().hide();
    $('.cover .inner-login').show()
})